### PR TITLE
remove comment

### PR DESCRIPTION
**Pull request by patrickriordan**

### CODE REVIEW

**Comment by patrickriordan** [comment]
atlantis plan

**Comment by iq-pe-atlas** [comment]
```diff
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vault_generic_secret.atlantis-global: Refreshing state...
aws_subnet.us-west-2b-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: subnet-1ce57c65)
aws_subnet.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: subnet-63e57c1a)
aws_subnet.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: subnet-4350eb08)
aws_subnet.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: subnet-4f82f315)
aws_subnet.us-west-2a-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: subnet-8054efcb)
aws_subnet.us-west-2c-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: subnet-ee83f2b4)
aws_route_table_association.private-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: rtbassoc-6afbcb10)
aws_route_table_association.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: rtbassoc-2bfdcd51)
aws_route_table_association.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: rtbassoc-27faca5d)
aws_route_table_association.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: rtbassoc-0bfece71)
aws_route_table_association.private-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: rtbassoc-e5f9c99f)
aws_route_table_association.private-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Refreshing state... (ID: rtbassoc-5afece20)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_route_table_association.private-us-west-2a-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      route_table_id:                                               "rtb-a20fb9c6"
      subnet_id:                                                    "${aws_subnet.us-west-2a-sfiq-k8s-staging-salesforceiq-com.id}"

  + aws_route_table_association.private-us-west-2b-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      route_table_id:                                               "rtb-a20fb9c6"
      subnet_id:                                                    "${aws_subnet.us-west-2b-sfiq-k8s-staging-salesforceiq-com.id}"

  + aws_route_table_association.private-us-west-2c-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      route_table_id:                                               "rtb-a20fb9c6"
      subnet_id:                                                    "${aws_subnet.us-west-2c-sfiq-k8s-staging-salesforceiq-com.id}"

  + aws_route_table_association.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      route_table_id:                                               "rtb-d18945b4"
      subnet_id:                                                    "${aws_subnet.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com.id}"

  + aws_route_table_association.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      route_table_id:                                               "rtb-d18945b4"
      subnet_id:                                                    "${aws_subnet.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com.id}"

  + aws_route_table_association.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      route_table_id:                                               "rtb-d18945b4"
      subnet_id:                                                    "${aws_subnet.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com.id}"

  + aws_subnet.us-west-2a-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      assign_ipv6_address_on_creation:                              "false"
      availability_zone:                                            "us-west-2a"
      cidr_block:                                                   "10.31.164.0/24"
      ipv6_cidr_block:                                              <computed>
      ipv6_cidr_block_association_id:                               <computed>
      map_public_ip_on_launch:                                      "false"
      tags.%:                                                       "5"
      tags.KubernetesCluster:                                       "sfiq-k8s-staging.salesforceiq.com"
      tags.Name:                                                    "us-west-2a.sfiq-k8s-staging.salesforceiq.com"
      tags.SubnetType:                                              "Private"
      tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "owned"
      tags.kubernetes.io/role/internal-elb:                         "1"
      vpc_id:                                                       "vpc-24c40441"

  + aws_subnet.us-west-2b-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      assign_ipv6_address_on_creation:                              "false"
      availability_zone:                                            "us-west-2b"
      cidr_block:                                                   "10.31.165.0/24"
      ipv6_cidr_block:                                              <computed>
      ipv6_cidr_block_association_id:                               <computed>
      map_public_ip_on_launch:                                      "false"
      tags.%:                                                       "5"
      tags.KubernetesCluster:                                       "sfiq-k8s-staging.salesforceiq.com"
      tags.Name:                                                    "us-west-2b.sfiq-k8s-staging.salesforceiq.com"
      tags.SubnetType:                                              "Private"
      tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "owned"
      tags.kubernetes.io/role/internal-elb:                         "1"
      vpc_id:                                                       "vpc-24c40441"

  + aws_subnet.us-west-2c-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      assign_ipv6_address_on_creation:                              "false"
      availability_zone:                                            "us-west-2c"
      cidr_block:                                                   "10.31.166.0/24"
      ipv6_cidr_block:                                              <computed>
      ipv6_cidr_block_association_id:                               <computed>
      map_public_ip_on_launch:                                      "false"
      tags.%:                                                       "5"
      tags.KubernetesCluster:                                       "sfiq-k8s-staging.salesforceiq.com"
      tags.Name:                                                    "us-west-2c.sfiq-k8s-staging.salesforceiq.com"
      tags.SubnetType:                                              "Private"
      tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "owned"
      tags.kubernetes.io/role/internal-elb:                         "1"
      vpc_id:                                                       "vpc-24c40441"

  + aws_subnet.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      assign_ipv6_address_on_creation:                              "false"
      availability_zone:                                            "us-west-2a"
      cidr_block:                                                   "10.31.161.0/24"
      ipv6_cidr_block:                                              <computed>
      ipv6_cidr_block_association_id:                               <computed>
      map_public_ip_on_launch:                                      "false"
      tags.%:                                                       "5"
      tags.KubernetesCluster:                                       "sfiq-k8s-staging.salesforceiq.com"
      tags.Name:                                                    "utility-us-west-2a.sfiq-k8s-staging.salesforceiq.com"
      tags.SubnetType:                                              "Utility"
      tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "owned"
      tags.kubernetes.io/role/elb:                                  "1"
      vpc_id:                                                       "vpc-24c40441"

  + aws_subnet.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      assign_ipv6_address_on_creation:                              "false"
      availability_zone:                                            "us-west-2b"
      cidr_block:                                                   "10.31.162.0/24"
      ipv6_cidr_block:                                              <computed>
      ipv6_cidr_block_association_id:                               <computed>
      map_public_ip_on_launch:                                      "false"
      tags.%:                                                       "5"
      tags.KubernetesCluster:                                       "sfiq-k8s-staging.salesforceiq.com"
      tags.Name:                                                    "utility-us-west-2b.sfiq-k8s-staging.salesforceiq.com"
      tags.SubnetType:                                              "Utility"
      tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "owned"
      tags.kubernetes.io/role/elb:                                  "1"
      vpc_id:                                                       "vpc-24c40441"

  + aws_subnet.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com
      id:                                                           <computed>
      assign_ipv6_address_on_creation:                              "false"
      availability_zone:                                            "us-west-2c"
      cidr_block:                                                   "10.31.163.0/24"
      ipv6_cidr_block:                                              <computed>
      ipv6_cidr_block_association_id:                               <computed>
      map_public_ip_on_launch:                                      "false"
      tags.%:                                                       "5"
      tags.KubernetesCluster:                                       "sfiq-k8s-staging.salesforceiq.com"
      tags.Name:                                                    "utility-us-west-2c.sfiq-k8s-staging.salesforceiq.com"
      tags.SubnetType:                                              "Utility"
      tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "owned"
      tags.kubernetes.io/role/elb:                                  "1"
      vpc_id:                                                       "vpc-24c40441"
Plan: 12 to add, 0 to change, 0 to destroy.

```

* To **discard** this plan click [here](atlantis.salesforceiq.com/lock?id=relateiq%252Fiac-k8s-staging%252F.%252Fdefault).

**Comment by patrickriordan** [comment]
atlantis apply

**Comment by iq-pe-atlas** [comment]
```diff
aws_subnet.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Creating...
  assign_ipv6_address_on_creation:                              "" => "false"
  availability_zone:                                            "" => "us-west-2b"
  cidr_block:                                                   "" => "10.31.162.0/24"
  ipv6_cidr_block:                                              "" => "<computed>"
  ipv6_cidr_block_association_id:                               "" => "<computed>"
  map_public_ip_on_launch:                                      "" => "false"
  tags.%:                                                       "" => "5"
  tags.KubernetesCluster:                                       "" => "sfiq-k8s-staging.salesforceiq.com"
  tags.Name:                                                    "" => "utility-us-west-2b.sfiq-k8s-staging.salesforceiq.com"
  tags.SubnetType:                                              "" => "Utility"
  tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "" => "owned"
  tags.kubernetes.io/role/elb:                                  "" => "1"
  vpc_id:                                                       "" => "vpc-24c40441"
aws_subnet.us-west-2b-sfiq-k8s-staging-salesforceiq-com: Creating...
  assign_ipv6_address_on_creation:                              "" => "false"
  availability_zone:                                            "" => "us-west-2b"
  cidr_block:                                                   "" => "10.31.165.0/24"
  ipv6_cidr_block:                                              "" => "<computed>"
  ipv6_cidr_block_association_id:                               "" => "<computed>"
  map_public_ip_on_launch:                                      "" => "false"
  tags.%:                                                       "" => "5"
  tags.KubernetesCluster:                                       "" => "sfiq-k8s-staging.salesforceiq.com"
  tags.Name:                                                    "" => "us-west-2b.sfiq-k8s-staging.salesforceiq.com"
  tags.SubnetType:                                              "" => "Private"
  tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "" => "owned"
  tags.kubernetes.io/role/internal-elb:                         "" => "1"
  vpc_id:                                                       "" => "vpc-24c40441"
aws_subnet.us-west-2a-sfiq-k8s-staging-salesforceiq-com: Creating...
  assign_ipv6_address_on_creation:                              "" => "false"
  availability_zone:                                            "" => "us-west-2a"
  cidr_block:                                                   "" => "10.31.164.0/24"
  ipv6_cidr_block:                                              "" => "<computed>"
  ipv6_cidr_block_association_id:                               "" => "<computed>"
  map_public_ip_on_launch:                                      "" => "false"
  tags.%:                                                       "" => "5"
  tags.KubernetesCluster:                                       "" => "sfiq-k8s-staging.salesforceiq.com"
  tags.Name:                                                    "" => "us-west-2a.sfiq-k8s-staging.salesforceiq.com"
  tags.SubnetType:                                              "" => "Private"
  tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "" => "owned"
  tags.kubernetes.io/role/internal-elb:                         "" => "1"
  vpc_id:                                                       "" => "vpc-24c40441"
aws_subnet.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Creating...
  assign_ipv6_address_on_creation:                              "" => "false"
  availability_zone:                                            "" => "us-west-2a"
  cidr_block:                                                   "" => "10.31.161.0/24"
  ipv6_cidr_block:                                              "" => "<computed>"
  ipv6_cidr_block_association_id:                               "" => "<computed>"
  map_public_ip_on_launch:                                      "" => "false"
  tags.%:                                                       "" => "5"
  tags.KubernetesCluster:                                       "" => "sfiq-k8s-staging.salesforceiq.com"
  tags.Name:                                                    "" => "utility-us-west-2a.sfiq-k8s-staging.salesforceiq.com"
  tags.SubnetType:                                              "" => "Utility"
  tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "" => "owned"
  tags.kubernetes.io/role/elb:                                  "" => "1"
  vpc_id:                                                       "" => "vpc-24c40441"
aws_subnet.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Creating...
  assign_ipv6_address_on_creation:                              "" => "false"
  availability_zone:                                            "" => "us-west-2c"
  cidr_block:                                                   "" => "10.31.163.0/24"
  ipv6_cidr_block:                                              "" => "<computed>"
  ipv6_cidr_block_association_id:                               "" => "<computed>"
  map_public_ip_on_launch:                                      "" => "false"
  tags.%:                                                       "" => "5"
  tags.KubernetesCluster:                                       "" => "sfiq-k8s-staging.salesforceiq.com"
  tags.Name:                                                    "" => "utility-us-west-2c.sfiq-k8s-staging.salesforceiq.com"
  tags.SubnetType:                                              "" => "Utility"
  tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "" => "owned"
  tags.kubernetes.io/role/elb:                                  "" => "1"
  vpc_id:                                                       "" => "vpc-24c40441"
aws_subnet.us-west-2c-sfiq-k8s-staging-salesforceiq-com: Creating...
  assign_ipv6_address_on_creation:                              "" => "false"
  availability_zone:                                            "" => "us-west-2c"
  cidr_block:                                                   "" => "10.31.166.0/24"
  ipv6_cidr_block:                                              "" => "<computed>"
  ipv6_cidr_block_association_id:                               "" => "<computed>"
  map_public_ip_on_launch:                                      "" => "false"
  tags.%:                                                       "" => "5"
  tags.KubernetesCluster:                                       "" => "sfiq-k8s-staging.salesforceiq.com"
  tags.Name:                                                    "" => "us-west-2c.sfiq-k8s-staging.salesforceiq.com"
  tags.SubnetType:                                              "" => "Private"
  tags.kubernetes.io/cluster/sfiq-k8s-staging.salesforceiq.com: "" => "owned"
  tags.kubernetes.io/role/internal-elb:                         "" => "1"
  vpc_id:                                                       "" => "vpc-24c40441"
aws_subnet.us-west-2a-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: subnet-a74ef5ec)
aws_route_table_association.private-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Creating...
  route_table_id: "" => "rtb-a20fb9c6"
  subnet_id:      "" => "subnet-a74ef5ec"
aws_subnet.us-west-2b-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: subnet-929900eb)
aws_route_table_association.private-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Creating...
  route_table_id: "" => "rtb-a20fb9c6"
  subnet_id:      "" => "subnet-929900eb"
aws_subnet.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: subnet-5149f21a)
aws_subnet.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: subnet-c486f79e)
aws_subnet.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: subnet-cd9801b4)
aws_route_table_association.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Creating...
  route_table_id: "" => "rtb-d18945b4"
  subnet_id:      "" => "subnet-c486f79e"
aws_route_table_association.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Creating...
  route_table_id: "" => "rtb-d18945b4"
  subnet_id:      "" => "subnet-cd9801b4"
aws_route_table_association.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Creating...
  route_table_id: "" => "rtb-d18945b4"
  subnet_id:      "" => "subnet-5149f21a"
aws_subnet.us-west-2c-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: subnet-b988f9e3)
aws_route_table_association.private-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Creating...
  route_table_id: "" => "rtb-a20fb9c6"
  subnet_id:      "" => "subnet-b988f9e3"
aws_route_table_association.private-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: rtbassoc-41f9c93b)
aws_route_table_association.utility-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: rtbassoc-b6f8c8cc)
aws_route_table_association.private-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: rtbassoc-57fbcb2d)
aws_route_table_association.utility-us-west-2a-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: rtbassoc-01fbcb7b)
aws_route_table_association.private-us-west-2c-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: rtbassoc-b7f8c8cd)
aws_route_table_association.utility-us-west-2b-sfiq-k8s-staging-salesforceiq-com: Creation complete after 0s (ID: rtbassoc-b3fdcdc9)

Apply complete! Resources: 12 added, 0 changed, 0 destroyed.

Outputs:

node_subnet_ids = [
    subnet-a74ef5ec,
    subnet-929900eb,
    subnet-b988f9e3
]

```

**Comment by iq-pe-atlas** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- path: `relateiq/iac-k8s-staging/.` workspace: `default`

**Pull request merged**
